### ISSUE TITLE
turn a snakebids app into a package

### ISSUE THREAD

**Issue by Remi-Gau** [akhanf/snakebids#220]
Starting to play with snakebids and trying to turn my project into a package.

https://github.com/Remi-Gau/bidsgnostic

But eventhough I have put my snakemake file and the associated scripts in the manifest, it seems that they cannot be found.

See the output below that I get in CI:

https://app.circleci.com/pipelines/github/Remi-Gau/bidsgnostic/3/workflows/5546d73c-64d7-4de1-a7db-da5f7506b259/jobs/3

```bash
/home/circleci/.pyenv/versions/3.8.16/lib/python3.8/site-packages/bids/config.py:39: FutureWarning: Setting 'extension_initial_dot' will be removed in pybids 0.16.
  warnings.warn("Setting 'extension_initial_dot' will be removed in pybids 0.16.",
Traceback (most recent call last):
  File "/home/circleci/.pyenv/versions/3.8.16/bin/bidsgnostic", line 8, in <module>
    sys.exit(main())
  File "/home/circleci/.pyenv/versions/3.8.16/lib/python3.8/site-packages/bidsgnostic/run.py", line 13, in main
    app = SnakeBidsApp(app_dir)
  File "/home/circleci/.pyenv/versions/3.8.16/lib/python3.8/site-packages/snakebids/app.py", line 62, in __init__
    raise FileNotFoundError('Snakefile not found must be defined or placed in workflow/Snakefile')
FileNotFoundError: Snakefile not found must be defined or placed in workflow/Snakefile

Exited with code exit status 1
```

**Comment by Remi-Gau** [comment]
OK I retarted by using the cookie cutter generated by `snakebids create` and that solved it.
